name: Docker Image CI tag

on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]*"
  pull_request:
    tags: 
      - "[0-9].[0-9].[0-9]*"


jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PATH }}
      - name: Docker build
        run: docker build -t ghcr.io/modulus/user-diesel:${{ GITHUB_REF }} .
      - name: Docker push
        run: docker push ghcr.io/modulus/user-diesel:${{ GITHUB_REF }}
